-- Basic
require("core.plugins")
require("core.mappings")
require("core.colors")
require("core.configs")

-- Plugins
require("plugins.treesitter")
require("plugins.neotree")
require("plugins.lsp")
require("plugins.cmp")
require("plugins.mason")
require("plugins.telescope")
require("plugins.nullls")
require("plugins.autopairs")
require("plugins.autotag")
require("plugins.buffline")
require("plugins.comments")
-- require("plugins.lualine")
require("plugins.outline")
require("plugins.toggleterm")
require("plugins.whichkey")
require("plugins.dashboard")
-- require("plugins.copilot")
