
[[keyboard.bindings]]
chars = "\u001B[27;5;105~"
key = "I"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[27;5;9~"
key = "Tab"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001B[27;6;9~"
key = "Tab"
mods = "Control|Shift"

[font]
normal = { family = "Liga SFMono Nerd Font", style = "Regular" }
bold = { family = "Liga SFMono Nerd Font", style = "SemiBold" }
size = 13

[cursor]
style = { shape = "Beam" }

[window]
dimensions = { columns = 80, lines = 25 }
opacity = 0.8
blur = true
startup_mode = "Maximized"
option_as_alt = "Both"
decorations = "None"

[env]
TERM = "xterm-256color"

[general]
import = ["~/.config/alacritty/themes/gruvbox-dark.toml"]
