import = ["~/.config/alacritty/themes/gruvbox-dark.toml"]

[font]
normal = { family = "Liga SFMono Nerd Font", style = "Regular" }
bold = { family = "Liga SFMono Nerd Font", style = "SemiBold" }
size = 15

[cursor]
style = { shape = "Beam" }

[window]
dimensions = { columns = 80, lines = 25 }
opacity = 0.8
blur = true
startup_mode = "Maximized"

[env]
TERM = "xterm-256color"
